lamps = [
    # id, x, y, width, [rotation]
    [1, 30, 51, 15],
    [2, 50, 51, 15],
    [3, 70, 51, 15],
    [4, 90, 51, 15],
    [5, 110, 51, 15],
    [6, 130, 51, 15],
    [7, 150, 51, 15],
    [8, 170, 51, 15],
    [9, 190, 51, 15],
    [10, 210, 51, 15],

    [20, 131, 59, 20, -52],

    [21, 150, 79, 15],
    [22, 170, 79, 15],
    [23, 190, 79, 15],
    [24, 210, 79, 15],

    # signal lamps
    [100, 100, 62, 12],
]

blocks = [
    # id, length, lamp_id
    [1, 800, 1],
    [2, 800, 2],
    [3, 800, 3],
    [4, 800, 4],
    [5, 800, 5],
    [6, 800, 6],
    [7, 800, 7],
    [8, 800, 8],
    [9, 800, 9],
    [10, 800, 10],

    [21, 800, 21],
    [22, 800, 22],
    [23, 800, 23],
    [24, 800, 24],
]

connections = [
    # start block id, end block id, [side block id] (for switches)
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],

    [6, 7],
    [7, 8],
    [8, 9],
    [9, 10],

    [21, 22],
    [22, 23],
    [23, 24],
]

signals = [
    # id, lamp_id, block_id, offset_m, name, dir (1 even, -1 odd)
    [20, 0, 1, 5, "End", -1],

    [1, 0, 1, 780, "6", 1],
    [2, 0, 2, 780, "4", 1],
    [3, 0, 3, 780, "2", 1],
    [21, 0, 2, 20, "2", -1],
    [22, 0, 3, 20, "3", -1],
    [23, 0, 4, 20, "4", -1],

    [50, 100, 4, 780, "1", 1],

    [30, 0, 10, 795, "End", 1],
    [31, 0, 24, 795, "End", 1],
]

background = "#508050"
