lamps = [
    # id, x, y, width, [rotation]
    [1, 9, 50, 17],
    [2, 35, 50, 17],
    [3, 61, 50, 17],
    [4, 87, 50, 17],
    [5, 113, 50, 17],

    [6, 132, 50, 17],
    [7, 158, 50, 17],
    [8, 184, 50, 17],
    [9, 210, 50, 17],
    [10, 236, 50, 17],

    [20, 134, 55, 30, -52],

    [21, 150, 78, 17],
    [22, 176, 78, 17],
    [23, 202, 78, 17],
    [24, 228, 78, 17],

    # signal lamps
    [100, 110, 62, 12],
    # chained signals, visible for debugging only
    [101, 22, 62, 12],
    [102, 48, 62, 12],
    [103, 74, 62, 12],
    [104, 170, 62, 12],
    [105, 196, 62, 12],
    [106, 222, 62, 12],
    [107, 248, 62, 12],
    [108, 188, 92, 12],
    [109, 214, 92, 12],
    [110, 240, 92, 12],
]

blocks = [
    # id, length, lamp_id
    [1, 1400, 1],
    [2, 1400, 2],
    [3, 1400, 3],
    [4, 1400, 4],
    [5, 200, 5],
    [6, 200, 6],
    [7, 1400, 7],
    [8, 1400, 8],
    [9, 1400, 9],
    [10, 1400, 10],

    [20, 100, 20],
    [21, 200, 21],
    [22, 1400, 22],
    [23, 1400, 23],
    [24, 1400, 24],
]

connections = [
    # start block id, end block id (in the even direction)
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],

    [6, 7],
    [7, 8],
    [8, 9],
    [9, 10],

    [20, 21],
    [21, 22],
    [22, 23],
    [23, 24],
]

switches = [
    # id, base block id, straight block id, side block id, split direction (1 even, -1 odd)
    [1, 5, 6, 20, 1],
]

signals = [
    # id, lamp_id, block_id, offset_m, name, direction (1 even, -1 odd)
    [30, 0, 1, 5, "EndL", -1],

    [1, 101, 1, 1380, "6", 1],   # main approach left
    [2, 102, 2, 1380, "4", 1],
    [3, 103, 3, 1380, "2", 1],

    [5, 104, 7, 1380, "10", 1],  # main cont right
    [6, 105, 8, 1380, "8", 1],
    [7, 106, 9, 1380, "6", 1],

    [10, 108, 22, 1380, "6", 1],  # switch right
    [11, 109, 23, 1380, "4", 1],

    [50, 100, 4, 1380, "1", 1],

    [31, 107, 10, 795, "EndR1", 1],
    [32, 110, 24, 795, "EndR2", 1],
]

background = "#508050"
