lamps = [
    # id, x, y, width, [height]
    [1, 10, 51, 15],
    [2, 30, 51, 15],
    [3, 50, 51, 15],
    [4, 70, 51, 15],
    [5, 90, 51, 15],
    [6, 110, 51, 15],
    [7, 130, 51, 15],
    [8, 150, 51, 15],
    [9, 170, 51, 15],
    [10, 190, 51, 15],
    [11, 210, 51, 15],
    [12, 230, 51, 15],

    # signal lamps
    [100, 100, 62, 12],
    [101, 100, 40, 12],
    [102, 180, 62, 12],
    [103, 180, 40, 12],
]

blocks = [
    # id, length, lamp_id
    [1, 800, 1],
    [2, 800, 2],
    [3, 800, 3],
    [4, 800, 4],
    [5, 800, 5],
    [6, 800, 6],
    [7, 800, 7],
    [8, 800, 8],
    [9, 800, 9],
    [10, 800, 10],
    [11, 800, 11],
    [12, 800, 12],
]

connections = [
    # start block id, end block id, [side block id] (for switches)
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
    [5, 6],
    [6, 7],
    [7, 8],
    [8, 9],
    [9, 10],
    [10, 11],
    [11, 12],
    [12, 1],
]

signals = [
    # id, lamp_id, block_id, offset_m, name, dir (1 even, -1 odd)
    [1, 100, 5, 780, "4", 1],
    [2, 101, 6, 20, "1", -1],
    [3, 102, 9, 780, "2", 1],
    [4, 103, 10, 20, "3", -1],
]

background = "#64a064"
