lamps = [
    # id, x, y, width, [rotation]
    [1, 30, 50, 17],
    [2, 56, 50, 17],
    [3, 82, 50, 17],
    [4, 108, 50, 17],
    [5, 134, 50, 17],

    [6, 153, 50, 17],
    [7, 179, 50, 17],
    [8, 205, 50, 17],
    [9, 231, 50, 17],
    [10, 257, 50, 17],

    [20, 147, 65, 28, 52],

    [21, 171, 78, 17],
    [22, 197, 78, 17],
    [23, 223, 78, 17],
    [24, 249, 78, 17],

    # signal lamps
    [100, 131, 62, 12],
    # chained signals, visible for debugging only
    [101, 43, 62, 12],
    [102, 69, 62, 12],
    [103, 95, 62, 12],
    [104, 191, 62, 12],
    [105, 217, 62, 12],
    [106, 243, 62, 12],
    [107, 269, 62, 12],
    [108, 209, 92, 12],
    [109, 235, 92, 12],
    [110, 261, 92, 12],
]

blocks = [
    # id, length, lamp_id
    [1, 1400, 1],
    [2, 1400, 2],
    [3, 1400, 3],
    [4, 1400, 4],
    [5, 200, 5],
    [6, 200, 6],
    [7, 1400, 7],
    [8, 1400, 8],
    [9, 1400, 9],
    [10, 1400, 10],

    [20, 100, 20],
    [21, 200, 21],
    [22, 1400, 22],
    [23, 1400, 23],
    [24, 1400, 24],
]

connections = [
    # start block id, end block id (in the even direction)
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],

    [6, 7],
    [7, 8],
    [8, 9],
    [9, 10],

    [20, 21],
    [21, 22],
    [22, 23],
    [23, 24],
]

switches = [
    # id, base block id, straight block id, side block id, split direction (1 even, -1 odd)
    [1, 5, 6, 20, 1],
]

spawners = [
    # block_id, spawn | despawn | both, [x, y]
    [1, "spawn", 1, 34],
    [10, "despawn"],
    [24, "despawn"],
]

signals = [
    # id, lamp_id, block_id, offset_m, name, direction (1 even, -1 odd)
    [30, 0, 1, 5, "EndL", -1],

    [1, 101, 1, 1380, "6", 1],   # main approach left
    [2, 102, 2, 1380, "4", 1],
    [3, 103, 3, 1380, "2", 1],

    [5, 104, 7, 1380, "10", 1],  # main cont right
    [6, 105, 8, 1380, "8", 1],
    [7, 106, 9, 1380, "6", 1],

    [10, 108, 22, 1380, "6", 1],  # switch right
    [11, 109, 23, 1380, "4", 1],

    [50, 100, 4, 1380, "1", 1],

    [31, 107, 10, 795, "EndR1", 1],
    [32, 110, 24, 795, "EndR2", 1],
]

background = "#508050"
